# Copy vcpkg + CUDA runtime DLLs next to the target executable (Windows).
if(NOT DEST OR NOT EXISTS "${DEST}")
    message(FATAL_ERROR "copy_runtime_dlls: DEST missing or does not exist: ${DEST}")
endif()
if(VCPKG_BIN AND EXISTS "${VCPKG_BIN}")
    file(GLOB _vcpkg_dlls "${VCPKG_BIN}/*.dll")
    foreach(_dll IN LISTS _vcpkg_dlls)
        file(COPY "${_dll}" DESTINATION "${DEST}")
    endforeach()
endif()
if(CUDA_BIN AND EXISTS "${CUDA_BIN}")
    file(GLOB _cuda_dlls "${CUDA_BIN}/cudart64_*.dll")
    foreach(_dll IN LISTS _cuda_dlls)
        file(COPY "${_dll}" DESTINATION "${DEST}")
    endforeach()
endif()
if(EXISTS "C:/cuda118/bin/cudart64_110.dll")
    file(COPY "C:/cuda118/bin/cudart64_110.dll" DESTINATION "${DEST}")
endif()
if(EXISTS "C:/cuda118/bin/cudart64_11.dll")
    file(COPY "C:/cuda118/bin/cudart64_11.dll" DESTINATION "${DEST}")
endif()
